/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import clasesYAtributos.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier_Andres Herrera Manjarrez
 */
public class CrearConsumo extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private ListasYmetodos base = new ListasYmetodos();
    private Matricula matricula;
    private Menu menu;

    private JPopupMenu emergenteTablaInfante;
    private JTable tablaInfantes;
    private JButton itenTablaInfante;
    private JScrollPane scrulTablaInfante;

    public CrearConsumo() {
        initComponents();
        emergenteTablaInfante = new JPopupMenu();
        scrulTablaInfante = new JScrollPane();
        tablaInfantes = base.getMatricula_Acudiente_PCMensualidad();
        itenTablaInfante = new JButton();

        emergenteTablaInfante.setLayout(null);

        scrulTablaInfante.setViewportView(tablaInfantes);

        scrulTablaInfante.setPreferredSize(new Dimension(400, 250));
        scrulTablaInfante.setAlignmentX(0);
        scrulTablaInfante.setAlignmentY(0);

        emergenteTablaInfante.add(scrulTablaInfante);
        emergenteTablaInfante.add(itenTablaInfante);

        itenTablaInfante.setText("Seleccionar");
        itenTablaInfante.setSize(40, 40);
        itenTablaInfante.setFont(new Font("arial", 2, 18));
        itenTablaInfante.setBackground(Color.orange);
        itenTablaInfante.addActionListener((ActionEvent eve) -> {
            Icon icono = new ImageIcon(getClass().getResource("/imgjpanel/escoger.png"));
            int confir = JOptionPane.showConfirmDialog(null, "Confirme su deción",
                    "Aviso", JOptionPane.YES_NO_OPTION, 3, icono);
            if (confir == JOptionPane.YES_OPTION) {
                DefaultTableModel m = (DefaultTableModel) tablaInfantes.getModel();
                int fila = tablaInfantes.getSelectedRow();
                if (fila == -1) {
                    JOptionPane.showMessageDialog(null, "1. seleccione la fila");
                } else {
                    String n = (String) m.getValueAt(fila, 0);
                    datosInfante(n);
                }
            }
        });

        datosDelInfante.setComponentPopupMenu(emergenteTablaInfante);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        datosDelInfante = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosDelMenu = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarInfante = new javax.swing.JButton();
        numeroDematricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarMenu = new javax.swing.JButton();
        numeroDEMenu = new javax.swing.JTextField();
        btnGenerarConsumo = new javax.swing.JButton();
        inicio = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 211, 70));
        setLayout(null);

        datosDelInfante.setEditable(false);
        datosDelInfante.setColumns(20);
        datosDelInfante.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        datosDelInfante.setRows(5);
        datosDelInfante.setToolTipText("Datos del Infante");
        jScrollPane1.setViewportView(datosDelInfante);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 320, 310);

        datosDelMenu.setEditable(false);
        datosDelMenu.setColumns(20);
        datosDelMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        datosDelMenu.setRows(5);
        datosDelMenu.setToolTipText("Datos del Menu");
        jScrollPane2.setViewportView(datosDelMenu);

        add(jScrollPane2);
        jScrollPane2.setBounds(510, 100, 400, 340);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Numero de matricula");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 170, 25);

        btnBuscarInfante.setBackground(new java.awt.Color(102, 255, 51));
        btnBuscarInfante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarInfante.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarInfante.setText("Buscar");
        btnBuscarInfante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInfanteActionPerformed(evt);
            }
        });
        add(btnBuscarInfante);
        btnBuscarInfante.setBounds(30, 60, 100, 30);

        numeroDematricula.setToolTipText("Nummero de matricula Del Infante");
        numeroDematricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDematriculaActionPerformed(evt);
            }
        });
        numeroDematricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDematriculaKeyTyped(evt);
            }
        });
        add(numeroDematricula);
        numeroDematricula.setBounds(210, 30, 140, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Numero del Menu");
        add(jLabel2);
        jLabel2.setBounds(510, 30, 170, 25);

        btnBuscarMenu.setBackground(new java.awt.Color(102, 255, 51));
        btnBuscarMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarMenu.setText("Buscar");
        btnBuscarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMenuActionPerformed(evt);
            }
        });
        add(btnBuscarMenu);
        btnBuscarMenu.setBounds(510, 60, 100, 30);

        numeroDEMenu.setToolTipText("Numero del Menu");
        numeroDEMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDEMenuKeyTyped(evt);
            }
        });
        add(numeroDEMenu);
        numeroDEMenu.setBounds(690, 30, 140, 25);

        btnGenerarConsumo.setBackground(new java.awt.Color(143, 255, 0));
        btnGenerarConsumo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGenerarConsumo.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerarConsumo.setText("Generar consumo");
        btnGenerarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarConsumoActionPerformed(evt);
            }
        });
        add(btnGenerarConsumo);
        btnGenerarConsumo.setBounds(360, 280, 140, 26);

        inicio.setBackground(new java.awt.Color(154, 0, 4));
        inicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inicio.setForeground(new java.awt.Color(0, 0, 0));
        inicio.setText("Inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        add(inicio);
        inicio.setBounds(360, 60, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void numeroDematriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDematriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDematriculaActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        removeAll();
        updateUI();
        menu m = new menu();
        m.setBounds(0, 0, 1000, 525);
        add(m.intconponente());
    }//GEN-LAST:event_inicioActionPerformed

    private void numeroDematriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDematriculaKeyTyped
        char c = evt.getKeyChar();
        if (c == '!' || c == ' ' || c == '¡') {
            evt.consume();
        }
    }//GEN-LAST:event_numeroDematriculaKeyTyped

    private void numeroDEMenuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDEMenuKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_numeroDEMenuKeyTyped

    private void btnBuscarInfanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInfanteActionPerformed
        String n = numeroDematricula.getText();
        datosInfante(n);
    }//GEN-LAST:event_btnBuscarInfanteActionPerformed

    private void btnBuscarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMenuActionPerformed

        menu = base.getMenu(numeroDEMenu.getText());

        if (menu.numeroMenu != null) {

            String datos = "**********************************************************\n"
                    + "Numero del Menu:  " + menu.getNumeroMenu()
                    + "\nCosto del Menu:  " + menu.getCostoMenu() + "$\n"
                    + "-------------------------------------------------------------------\n";
            String[] auxi1 = new String[5];
            String[] auxi2 = new String[5];
            String[] auxi5 = new String[5];
            if (menu.getNombrePlatos().contains("¡")) {
                auxi1 = (menu.getNombrePlatos()).split("¡");
                auxi2 = (menu.getIngredientes()).split("¡");
                auxi5 = (menu.getCostoDelosPlato()).split("¡");
            } else {
                auxi1[0] = menu.getNombrePlatos();
                auxi2[0] = menu.getIngredientes();
                auxi5[0] = menu.getCostoDelosPlato();
            }

            for (int i = 0; i < auxi1.length; i++) {
                if (auxi1[i] != null) {
                    datos += ("\nPlato N° " + (i + 1) + " : " + auxi1[i])
                            + "\nCosto del plato:  " + auxi5[i]
                            + "\nIgredientes:\n"
                            + auxi2[i];
                    
//                    String[] auxi3 = (auxi2[i]).split(" ");
//                    int p = 1;
//                    for (String auxi4 : auxi3) {
//                        if (p % 4 == 0) {
//                            datos += " " + auxi4 + "\n";
//                        } else {
//                            datos += " " + auxi4;
//                        }
//                        p++;
//                    }
                    datos += "\n-------------------------------------------------------------------";
                }
            }

            datosDelMenu.setText(datos);
            numeroDEMenu.setText("");

        } else {
            datosDelMenu.setText("");
        }
    }//GEN-LAST:event_btnBuscarMenuActionPerformed

    private void btnGenerarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarConsumoActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imgjpanel/escoger.png"));
        int confir = JOptionPane.showConfirmDialog(null, "Confirme su deción",
                "Aviso", JOptionPane.YES_NO_OPTION, 3, icono);
        if (confir == JOptionPane.YES_OPTION) {
            if (datosDelInfante.getText().equals("") || datosDelMenu.getText().equals("")) {
                Icon ic = new ImageIcon(getClass().getResource("/imgjpanel/advertencia.png"));
                JOptionPane.showMessageDialog(null, "Primero busque el  menú y \n"
                        + " el infante que va a recibirlo", "Advertencia", JOptionPane.INFORMATION_MESSAGE, ic);
            } else {

                consumoDeInfante con = new consumoDeInfante(matricula.getNumeroMatricula(),
                        String.valueOf(new SimpleDateFormat("dd/MM/YYYY").format(new Date())), menu.getNumeroMenu(), menu.getCostoMenu());
                if (base.addConsumoDeUnInfante(con) == true) {
                    datosDelInfante.setText("");
                    datosDelMenu.setText("");
                    JOptionPane.showMessageDialog(null, "Proceso realizado con existo\n"
                            + "Se le asignado el menú: " + menu.getNumeroMenu() + "\n"
                            + "Al infante con el numero matricula: " + matricula.getNumeroMatricula(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_btnGenerarConsumoActionPerformed

    public JPanel iten() {
        return this;
    }

    private void datosInfante(String n) {
        matricula = base.getInfante(n);

        if (!"Inexistente".equalsIgnoreCase(matricula.siSeDioBajaAlNinoFecha)) {
            String m = "Debido a que\n"
                    + "Fecha de baja es distinto de Inexistente\n"
                    + "No se le podrán realizar consumos al infante\n"
                    + "Con la matricula "+matricula.numeroMatricula;
            JOptionPane.showMessageDialog(null, m, "Advertencia",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (matricula.numeroMatricula != null) {

            numeroDematricula.setText("");

            String datos = "Numero de Matricula: " + matricula.getNumeroMatricula()
                    + "\nNombre: " + matricula.getNombreDeInfante()
                    + "\nFecha de Ingreso: " + matricula.getFechaIngresoGuarderia()
                    + "\nFecha de Nacimiento: " + matricula.getFechaNacimiento()
                    + "\nFecha de Baja del Ifante: " + matricula.getSiSeDioBajaAlNinoFecha()
                    + "\nAlergia(s) del Infante: " + matricula.getAlergiaDelInfante();
            datosDelInfante.setText(datos);
        } else {
            datosDelInfante.setText("");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarInfante;
    private javax.swing.JButton btnBuscarMenu;
    private javax.swing.JButton btnGenerarConsumo;
    private javax.swing.JTextArea datosDelInfante;
    private javax.swing.JTextArea datosDelMenu;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numeroDEMenu;
    private javax.swing.JTextField numeroDematricula;
    // End of variables declaration//GEN-END:variables
}
