/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.WindowConstants;
import clasesYAtributos.*;
import java.awt.Color;
import java.io.File;

/**
 *
 * @author Javier_Andres Herrera Manjarrez
 */
public class registroInfante extends javax.swing.JDialog {

    /**
     * Creates new form registroInfante
     */
    int queTipo, numTabla;
    String numMatricula;
    ListasYmetodos base = new ListasYmetodos();

    public registroInfante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCostea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numeroDeCuenta = new javax.swing.JTextField();
        nombreCostea = new javax.swing.JTextField();
        telefonCostea = new javax.swing.JTextField();
        direccionCostea = new javax.swing.JTextField();
        DNICostea = new javax.swing.JTextField();
        panelDatosInfante = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        alergiaInfante = new javax.swing.JTextField();
        nombreInfante = new javax.swing.JTextField();
        numeroDeMatricula = new javax.swing.JTextField();
        spiAnioIngrso = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        spidiaIngreso = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        spiMesIngreso = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        spidia = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        spiMes = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        spiAnio = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        siSedioDeBaja = new javax.swing.JTextField();
        panelCostea1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        relacionConElInfante = new javax.swing.JTextField();
        nombreAcudiente = new javax.swing.JTextField();
        telefonAcudiente = new javax.swing.JTextField();
        direccionAcudiente = new javax.swing.JTextField();
        DNIAcudiente = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 233, 108));
        setPreferredSize(new java.awt.Dimension(1050, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCostea.setBackground(new java.awt.Color(255, 251, 119));
        panelCostea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 251, 119)), "Datos de la persona que costea la mensualidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        panelCostea.setPreferredSize(new java.awt.Dimension(436, 214));
        panelCostea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Numero de cuenta");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre(s) y Apellido(s)");
        jLabel2.setToolTipText("");
        panelCostea.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Direccion");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("DNI");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Numero de Telefono");
        jLabel5.setToolTipText("");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 25));

        numeroDeCuenta.setToolTipText("Numero de cuenta que posee");
        numeroDeCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDeCuentaKeyTyped(evt);
            }
        });
        panelCostea.add(numeroDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, 35));

        nombreCostea.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        nombreCostea.setToolTipText("Nombre(s) y Apellido(s)");
        nombreCostea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCosteaActionPerformed(evt);
            }
        });
        nombreCostea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreCosteaKeyTyped(evt);
            }
        });
        panelCostea.add(nombreCostea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 250, 35));

        telefonCostea.setToolTipText("Numero de telefono movil");
        telefonCostea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonCosteaKeyTyped(evt);
            }
        });
        panelCostea.add(telefonCostea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 250, 35));

        direccionCostea.setToolTipText("Direccion");
        direccionCostea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionCosteaKeyTyped(evt);
            }
        });
        panelCostea.add(direccionCostea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 250, 35));

        DNICostea.setToolTipText("DNI o numero de identificación o c.c.");
        DNICostea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DNICosteaKeyTyped(evt);
            }
        });
        panelCostea.add(DNICostea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 250, 35));

        getContentPane().add(panelCostea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 480, 250));

        panelDatosInfante.setBackground(new java.awt.Color(255, 251, 119));
        panelDatosInfante.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 251, 119)), "Datos infante", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        panelDatosInfante.setPreferredSize(new java.awt.Dimension(436, 214));
        panelDatosInfante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Si sedio de baja fecha");
        jLabel12.setToolTipText("");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDatosInfante.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 25));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre(s) y Apellido(s)");
        jLabel13.setToolTipText("");
        panelDatosInfante.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Numero de matricula  ");
        jLabel14.setToolTipText("");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDatosInfante.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 25));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Fecha Nacimiento  ");
        jLabel15.setToolTipText("");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDatosInfante.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 25));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Fecha de Ingreso  ");
        jLabel16.setToolTipText("");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDatosInfante.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 25));

        alergiaInfante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alergiaInfanteKeyTyped(evt);
            }
        });
        panelDatosInfante.add(alergiaInfante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, 35));

        nombreInfante.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        nombreInfante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreInfanteActionPerformed(evt);
            }
        });
        nombreInfante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreInfanteKeyTyped(evt);
            }
        });
        panelDatosInfante.add(nombreInfante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 250, 35));

        numeroDeMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeMatriculaActionPerformed(evt);
            }
        });
        numeroDeMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDeMatriculaKeyTyped(evt);
            }
        });
        panelDatosInfante.add(numeroDeMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 250, 35));

        spiAnioIngrso.setFont(new java.awt.Font("Segoe UI", 0, 14));
        panelDatosInfante.add(spiAnioIngrso, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 70, 25));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Año: ");
        panelDatosInfante.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 25));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Dia: ");
        panelDatosInfante.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 25));

        spidiaIngreso.setFont(new java.awt.Font("Segoe UI", 0, 14));
        spidiaIngreso.setEditor(new javax.swing.JSpinner.NumberEditor(spidiaIngreso, ""));
        panelDatosInfante.add(spidiaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 50, 25));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Mes: ");
        panelDatosInfante.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 25));

        spiMesIngreso.setFont(new java.awt.Font("Segoe UI", 0, 14));
        panelDatosInfante.add(spiMesIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 50, 25));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Dia: ");
        panelDatosInfante.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 25));

        spidia.setFont(new java.awt.Font("Segoe UI", 0, 14));
        spidia.setEditor(new javax.swing.JSpinner.NumberEditor(spidia, ""));
        panelDatosInfante.add(spidia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 50, 25));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Mes: ");
        panelDatosInfante.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 25));

        spiMes.setFont(new java.awt.Font("Segoe UI", 0, 14));
        panelDatosInfante.add(spiMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 50, 25));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Año: ");
        panelDatosInfante.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 25));

        spiAnio.setFont(new java.awt.Font("Segoe UI", 0, 14));
        panelDatosInfante.add(spiAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 70, 25));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Alergia  ");
        jLabel23.setToolTipText("");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDatosInfante.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 25));

        siSedioDeBaja.setToolTipText(" sino");
        siSedioDeBaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                siSedioDeBajaKeyTyped(evt);
            }
        });
        panelDatosInfante.add(siSedioDeBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 250, 35));

        getContentPane().add(panelDatosInfante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 67, 480, 290));

        panelCostea1.setBackground(new java.awt.Color(255, 251, 119));
        panelCostea1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 251, 119)), "Acudiente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        panelCostea1.setPreferredSize(new java.awt.Dimension(436, 214));
        panelCostea1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Relacion Con el Infante");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre(s) y Apellido(s)");
        jLabel7.setToolTipText("");
        panelCostea1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Direccion");
        jLabel8.setToolTipText("");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 25));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("DNI");
        jLabel9.setToolTipText("");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Numero de Telefono");
        jLabel10.setToolTipText("");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCostea1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 25));

        relacionConElInfante.setToolTipText("Cual es la relacion del acudiente con el infate");
        relacionConElInfante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                relacionConElInfanteKeyTyped(evt);
            }
        });
        panelCostea1.add(relacionConElInfante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, 35));

        nombreAcudiente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        nombreAcudiente.setToolTipText("Nombre(s) y Apellido(s)");
        nombreAcudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAcudienteActionPerformed(evt);
            }
        });
        nombreAcudiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreAcudienteKeyTyped(evt);
            }
        });
        panelCostea1.add(nombreAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 250, 35));

        telefonAcudiente.setToolTipText("Numero de telefono movil");
        telefonAcudiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonAcudienteKeyTyped(evt);
            }
        });
        panelCostea1.add(telefonAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 250, 35));

        direccionAcudiente.setToolTipText("Direccion");
        direccionAcudiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionAcudienteKeyTyped(evt);
            }
        });
        panelCostea1.add(direccionAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 250, 35));

        DNIAcudiente.setToolTipText("DNI o numero de identificación o c.c.");
        DNIAcudiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DNIAcudienteKeyTyped(evt);
            }
        });
        panelCostea1.add(DNIAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 250, 35));

        getContentPane().add(panelCostea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 67, 480, 250));

        btnCancelar.setBackground(new java.awt.Color(255, 101, 53));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("dele un click al boton para añadir a el nuevo infante");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 190, 42));
        btnCancelar.getAccessibleContext().setAccessibleName("btnRegistrar");

        btnAnadir.setBackground(new java.awt.Color(154, 247, 32));
        btnAnadir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(0, 0, 0));
        btnAnadir.setText("Añadir");
        btnAnadir.setToolTipText("dele un click al boton para añadir a el nuevo infante");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 190, 42));

        btnAceptar.setBackground(new java.awt.Color(154, 247, 70));
        btnAceptar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreCosteaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCosteaKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || c == '!') {
            evt.consume();
        }
        if (nombreCostea.getText().length() == 0 && c == ' ') {
            evt.consume();
        }
        if (nombreCostea.getText().endsWith(" ")) {// el ultimo caracter es un espacio
            if (c == ' ') {
                evt.consume();
            }
        }
        if(nombreCostea.getText().length()==200){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Maximo de caracteres 200","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nombreCosteaKeyTyped

    private void nombreCosteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCosteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCosteaActionPerformed

    private void nombreInfanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInfanteActionPerformed

    }//GEN-LAST:event_nombreInfanteActionPerformed

    private void nombreInfanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreInfanteKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || c == '!') {
            evt.consume();
        }
        if (nombreInfante.getText().length() == 0 && c == ' ') {
            evt.consume();
        }
        if (nombreInfante.getText().endsWith(" ")) {// el ultimo caracter es un espacio
            if (c == ' ') {
                evt.consume();
            }
        }
        if(nombreInfante.getText().length()==200){
        evt.consume();
         JOptionPane.showMessageDialog(null,"Maximo de caracteres 200","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nombreInfanteKeyTyped

    private void nombreAcudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAcudienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAcudienteActionPerformed

    private void nombreAcudienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreAcudienteKeyTyped
        char c = evt.getKeyChar();
        if (c == '!') {
            evt.consume();
        }
        if (nombreAcudiente.getText().length() == 0 && c == ' ') {
            evt.consume();
        }
        if (nombreAcudiente.getText().endsWith(" ")) {// el ultimo caracter es un espacio
            if (c == ' ') {
                evt.consume();
            }
        }
        if(nombreAcudiente.getText().length()==200){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Maximo de caracteres 200","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nombreAcudienteKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imgjpanel/escoger.png"));
        int confir = JOptionPane.showConfirmDialog(null, "Esta seguro de cancelar el registro",
                "Confirme", JOptionPane.YES_NO_OPTION, JOptionPane.DEFAULT_OPTION, icono);
        if (confir == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void DNICosteaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DNICosteaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (DNICostea.getText().length() == 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Maximo de caracteres 10","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_DNICosteaKeyTyped

    private void telefonCosteaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonCosteaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (telefonCostea.getText().length() == 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Maximo de caracteres 10","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_telefonCosteaKeyTyped

    private void DNIAcudienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DNIAcudienteKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (DNIAcudiente.getText().length() == 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Maximo de caracteres 10","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_DNIAcudienteKeyTyped

    private void telefonAcudienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonAcudienteKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (telefonAcudiente.getText().length() == 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Maximo de caracteres 10","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_telefonAcudienteKeyTyped

    private void numeroDeMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDeMatriculaKeyTyped
        char c = evt.getKeyChar();
        if (c == '!' || c == ' ') {
            evt.consume();
        }
        if(!Character.isDigit(c)){
         evt.consume();
        }
        if(numeroDeMatricula.getText().length() == 40){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Maximo de caracteres 40","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_numeroDeMatriculaKeyTyped

    private void alergiaInfanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alergiaInfanteKeyTyped
        char c = evt.getKeyChar();
        if (c == '!') {
            evt.consume();
        }
        if (alergiaInfante.getText().length() == 0 && c == ' ') {
            evt.consume();
        }
        if (alergiaInfante.getText().endsWith(" ")) {// el ultimo caracter es un espacio
            if (c == ' ') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_alergiaInfanteKeyTyped

    private void direccionCosteaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionCosteaKeyTyped
        char c = evt.getKeyChar();
        if (c == '!') {
            evt.consume();
        }
        if (direccionCostea.getText().length() == 0 && c == ' ') {
            evt.consume();
        }
        if (direccionCostea.getText().endsWith(" ")) {// el ultimo caracter es un espacio
            if (c == ' ') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_direccionCosteaKeyTyped

    private void numeroDeCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDeCuentaKeyTyped
        char c = evt.getKeyChar();
        if (c == '!' || c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_numeroDeCuentaKeyTyped

    private void direccionAcudienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionAcudienteKeyTyped
        char c = evt.getKeyChar();
        if (c == '!') {
            evt.consume();
        }
        if (direccionAcudiente.getText().length() == 0 && c == ' ') {
            evt.consume();
        }
        if (direccionAcudiente.getText().endsWith(" ")) {// el ultimo caracter es un espacio
            if (c == ' ') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_direccionAcudienteKeyTyped

    private void relacionConElInfanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_relacionConElInfanteKeyTyped
        char c = evt.getKeyChar();
        if (c == '!') {
            evt.consume();
        }
        if (relacionConElInfante.getText().length() == 0 && c == ' ') {
            evt.consume();
        }
        if (relacionConElInfante.getText().endsWith(" ")) {// el ultimo caracter es un espacio
            if (c == ' ') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_relacionConElInfanteKeyTyped

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        if(btnAceptarYAnadir() == true){
            incluirdatos();
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void siSedioDeBajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siSedioDeBajaKeyTyped
        char c = evt.getKeyChar();
        if (c == '!' || c == ' ') {
            evt.consume();
        }
        if (siSedioDeBaja.getText().length() == 11) {
            evt.consume();
        }
        if(siSedioDeBaja.getText().length()==15){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Maximo de caracteres 15","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_siSedioDeBajaKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(btnAceptarYAnadir() == true){
            incluirdatos();
            dispose();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void numeroDeMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDeMatriculaActionPerformed

    

    public void tipoDeJDialog(int num) {
        queTipo = num;
        resto();
    }

    public void datosDelaparaLaestraccion(String numMatricula) {
        this.numMatricula = numMatricula;
       
    }

    private void resto() {
        String[] fecha = new String[3];
        String[] fechaIngreso = new String[3];
        nombreInfante.setToolTipText("nombre(s) y apellido(s)");
        numeroDeMatricula.setToolTipText("Numero de matricula");
        alergiaInfante.setToolTipText("Alergias que posee el infante");
        if (queTipo == 1) {
            btnAnadir.setVisible(false);
            btnCancelar.setVisible(false);
            /**
             *llenar los arrays
             * obtener los datos
             * eliminar los datos en la posicion indicada
             * lleno un txt
             * 
             */
            
            Matricula matricula = base.getInfante(numMatricula);
            Acudiente acudiente = base.getAcudiente(numMatricula);
            PersonaCosteaMensualidad perCostea = base.getperCostea(numMatricula);
            
            String auxi = matricula.fechaNacimiento;
            fecha = auxi.split("/");
            
            auxi = matricula.fechaIngresoGuarderia;
            fechaIngreso = auxi.split("/");
            numeroDeMatricula.setText(matricula.numeroMatricula);
            numeroDeMatricula.setEditable(false);
            numeroDeMatricula.setToolTipText("Numero de matricula no editable");
            alergiaInfante.setText(matricula.alergiaDelInfante);
            nombreInfante.setText(matricula.nombreDeInfante);
            siSedioDeBaja.setText(matricula.siSeDioBajaAlNinoFecha);
            
            nombreAcudiente.setText(acudiente.Nombre);
            direccionAcudiente.setText(acudiente.direccion);
            telefonAcudiente.setText(acudiente.numeroTelefono);
            DNIAcudiente.setText(acudiente.DNI);
            relacionConElInfante.setText(acudiente.relacionConInfante);
            
            direccionCostea.setText(perCostea.acudiente.direccion);
            nombreCostea.setText(perCostea.acudiente.Nombre);
            DNICostea.setText(perCostea.acudiente.DNI);
            numeroDeCuenta.setText(perCostea.numeroDeCuenta);
            telefonCostea.setText(perCostea.acudiente.numeroTelefono);

           
            
            
      
        } else {
            siSedioDeBaja.setEditable(false);
            siSedioDeBaja.setText("Inexistente");
            btnAceptar.setVisible(false);

            Date daano = new Date();
            SimpleDateFormat fe = new SimpleDateFormat("dd-MM-YYYY");
            String auxi = String.valueOf(fe.format(daano));
            fecha = auxi.split("-");

        }

        ///   Modelo dia JSpinner
        modeloDia = new SpinnerNumberModel();
        modeloDia.setMaximum(31);
        modeloDia.setMinimum(1);
        modeloDia.setValue(Integer.parseInt(fecha[0]));
        spidia.setModel(modeloDia);
        spidia.setEditor(new JSpinner.DefaultEditor(spidia));

        SpinnerNumberModel modeloMes = new SpinnerNumberModel();
        modeloMes.setMaximum(12);
        modeloMes.setMinimum(1);
        modeloMes.setValue(Integer.parseInt(fecha[1]));
        spiMes.setModel(modeloMes);
        spiMes.setEditor(new JSpinner.DefaultEditor(spiMes));

        SpinnerNumberModel modeloAnio = new SpinnerNumberModel();
        modeloAnio.setMaximum(3000);
        modeloAnio.setMinimum(1910);
        modeloAnio.setValue(Integer.parseInt(fecha[2]));
        spiAnio.setModel(modeloAnio);
        spiAnio.setEditor(new JSpinner.DefaultEditor(spiAnio));

        //*********************************************************************
        //*********************************************************************
        //                   Fecha de ingreso
        SpinnerNumberModel modeloDiaIngreso = new SpinnerNumberModel();
        modeloDiaIngreso.setMaximum(31);
        modeloDiaIngreso.setMinimum(1);
        if (queTipo == 1) {
            modeloDiaIngreso.setValue(Integer.parseInt(fechaIngreso[0]));
        } else {
            modeloDiaIngreso.setValue(Integer.parseInt(fecha[0]));
        }
        spidiaIngreso.setModel(modeloDiaIngreso);
        spidiaIngreso.setEditor(new JSpinner.DefaultEditor(spidiaIngreso));

        SpinnerNumberModel modeloMesIngreso = new SpinnerNumberModel();
        modeloMesIngreso.setMaximum(31);
        modeloMesIngreso.setMinimum(1);
        if (queTipo == 1) {
            modeloMesIngreso.setValue(Integer.parseInt(fechaIngreso[1]));
        } else {
            modeloMesIngreso.setValue(Integer.parseInt(fecha[1]));
        }
        spiMesIngreso.setModel(modeloMesIngreso);
        spiMesIngreso.setEditor(new JSpinner.DefaultEditor(spiMesIngreso));

        SpinnerNumberModel modeloAnioIngreso = new SpinnerNumberModel();
        modeloAnioIngreso.setMaximum(3000);
        modeloAnioIngreso.setMinimum(1910);
        if (queTipo == 1) {
            modeloAnioIngreso.setValue(Integer.parseInt(fechaIngreso[2]));
        } else {
            modeloAnioIngreso.setValue(Integer.parseInt(fecha[2]));
        }
        spiAnioIngrso.setModel(modeloAnioIngreso);
        spiAnioIngrso.setEditor(new JSpinner.DefaultEditor(spiAnioIngrso));
    }
//*********************************************************************************************************************
    private void incluirdatos() {
        String fechaNAcimeiento = String.valueOf(spidia.getValue()) + "/" + String.valueOf(spiMes.getValue())
                + "/" + String.valueOf(spiAnio.getValue());
        String fechaIngreso = String.valueOf(spidiaIngreso.getValue()) + "/"
                + String.valueOf(spiMesIngreso.getValue()) + "/" + String.valueOf(spiAnioIngrso.getValue());

        Acudiente acudiente = new Acudiente(DNIAcudiente.getText(), nombreAcudiente.getText(),
                direccionAcudiente.getText(), telefonAcudiente.getText(),
                relacionConElInfante.getText());

        PersonaCosteaMensualidad per = new PersonaCosteaMensualidad(numeroDeCuenta.getText());
        per.acudiente = new Acudiente(DNICostea.getText(), nombreCostea.getText(), direccionCostea.getText(),
                telefonCostea.getText(), "");

        Matricula infate = new Matricula(numeroDeMatricula.getText(), nombreInfante.getText(), fechaNAcimeiento, fechaIngreso,
                siSedioDeBaja.getText(), alergiaInfante.getText());
        if(base.addInfate(infate, acudiente, per,queTipo)== true){
            numeroDeMatricula.setText("");nombreInfante.setText("");alergiaInfante.setText("");
            nombreAcudiente.setText("");direccionAcudiente.setText("");telefonAcudiente.setText("");
            DNIAcudiente.setText("");relacionConElInfante.setText("");direccionCostea.setText("");
            nombreCostea.setText("");DNICostea.setText("");numeroDeCuenta.setText("");telefonCostea.setText("");
        }
        
        
    }
//*********************************************************************************************************************
    private boolean btnAceptarYAnadir() {
        boolean confi = true;
        if (nombreInfante.getText().equals("") || alergiaInfante.getText().equals("")
                || numeroDeMatricula.getText().equals("") ||/*Acudiente*/ nombreAcudiente.getText().equals("")
                || direccionAcudiente.getText().equals("") || telefonAcudiente.getText().equals("")
                || DNIAcudiente.getText().equals("") || relacionConElInfante.getText().equals("")
                ||/*Acudiente*/ /*Persona costea*/ direccionCostea.getText().equals("") || nombreCostea.getText().equals("")
                || DNICostea.getText().equals("") || numeroDeCuenta.getText().equals("")
                || telefonCostea.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "No deje campo sin rellenar \n"
                    + "si el dato no existe digite Inexistente ", "Aviso", JOptionPane.WARNING_MESSAGE);
           confi=false;
        } 
        Icon icono = new ImageIcon(getClass().getResource("/imgjpanel" + File.separator + "escoger.png"));
        int confir = JOptionPane.showConfirmDialog(null, "Confirme",
                "Confirme", JOptionPane.YES_NO_OPTION, JOptionPane.DEFAULT_OPTION, icono);
        if (confir == JOptionPane.YES_OPTION) {
            confi = true;
        }
        return confi;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNIAcudiente;
    private javax.swing.JTextField DNICostea;
    private javax.swing.JTextField alergiaInfante;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField direccionAcudiente;
    private javax.swing.JTextField direccionCostea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreAcudiente;
    private javax.swing.JTextField nombreCostea;
    private javax.swing.JTextField nombreInfante;
    private javax.swing.JTextField numeroDeCuenta;
    private javax.swing.JTextField numeroDeMatricula;
    private javax.swing.JPanel panelCostea;
    private javax.swing.JPanel panelCostea1;
    private javax.swing.JPanel panelDatosInfante;
    private javax.swing.JTextField relacionConElInfante;
    private javax.swing.JTextField siSedioDeBaja;
    private javax.swing.JSpinner spiAnio;
    private javax.swing.JSpinner spiAnioIngrso;
    private javax.swing.JSpinner spiMes;
    private javax.swing.JSpinner spiMesIngreso;
    private javax.swing.JSpinner spidia;
    private javax.swing.JSpinner spidiaIngreso;
    private javax.swing.JTextField telefonAcudiente;
    private javax.swing.JTextField telefonCostea;
    // End of variables declaration//GEN-END:variables
    SpinnerNumberModel modeloDia;
}
